'use strict';
(()=>{
  let ready=false,pendingStock=null;
  const el=id=>document.getElementById('advanced-'+id);
  const kindNames={receipt:'Приход',reserve:'Резерв',release:'Освободить резерв',consume:'Списать в заказ',writeoff:'Списать свободный остаток'};
  const download64=(content,name,mime)=>download(Uint8Array.from(atob(content),c=>c.charCodeAt(0)),name,mime);
  const bytes64=async file=>{const bytes=new Uint8Array(await file.arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(text);};
  async function action(button,callback){if(button.disabled)return;button.disabled=true;try{await callback();}catch(error){el('status').textContent=error.message;notify(error.message,true);}finally{button.disabled=false;}}
  async function documents(kind){
    collectForm();const profiles=(await api('/api/workspace/list',{kind:'profile'})).items;
    const payload={project:structuredClone(project),profile:profiles[0]?.data||{}};
    if(kind==='docx'&&el('template-file').files[0]){const file=el('template-file').files[0];if(file.size>2097152)throw Error('Шаблон Word должен быть до 2 МБ.');payload.template=await bytes64(file);}
    const result=await api(kind==='docx'?'/api/export-docx':'/api/export-editable-xlsx',payload);
    const ext=kind==='docx'?'docx':'xlsx';download64(result.content,safeFilename(project.project.title)+(ext==='docx'?'_customer':'_editable_calculation')+'.'+ext,ext==='docx'?'application/vnd.openxmlformats-officedocument.wordprocessingml.document':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');el('status').textContent='Документ подготовлен.';
  }
  async function refreshStock(){
    const [catalog,orders,state]=await Promise.all([api('/api/workspace/list',{kind:'catalog'}),api('/api/workspace/list',{kind:'order'}),api('/api/stock/status',{})]);
    const itemValue=el('stock-item').value,orderValue=el('stock-order').value;
    el('stock-item').innerHTML='<option value="">Выберите материал</option>'+catalog.items.filter(row=>row.data.category==='material').map(row=>`<option value="${esc(row.id)}">${esc(row.name)} · ${esc(row.data.unit)} · ${esc(row.data.article)}</option>`).join('');
    el('stock-order').innerHTML='<option value="">Выберите сохранённый заказ</option>'+orders.items.map(row=>`<option value="${esc(row.id)}">${esc(row.name)}</option>`).join('');el('stock-item').value=itemValue;el('stock-order').value=orderValue;
    const names=new Map([...catalog.items.map(row=>[row.id,row.name]),...state.items.map(row=>[row.item_id,row.name])]);
    el('stock-balances').innerHTML=state.items.length?'<table class="workspace-table"><tr><th>Материал</th><th>Единица</th><th>На складе</th><th>В резерве</th><th>Свободно</th></tr>'+state.items.map(row=>`<tr><td>${esc(row.name)}</td><td>${esc(row.unit)}</td><td>${esc(row.on_hand)}</td><td>${esc(row.reserved)}</td><td>${esc(row.available)}</td></tr>`).join('')+'</table>':'<p>Остатки ещё не внесены. Используйте операцию «Приход».</p>';
    el('stock-reservations').innerHTML=state.reservations.length?'<h3>Резервы заказов</h3><table class="workspace-table"><tr><th>Заказ</th><th>Материал</th><th>Количество</th></tr>'+state.reservations.map(row=>`<tr><td>${esc(orders.items.find(order=>order.id===row.order_id)?.name||row.order_id)}</td><td>${esc(names.get(row.item_id)||row.item_id)}</td><td>${esc(row.quantity)}</td></tr>`).join('')+'</table>':'';
    el('stock-history').innerHTML=state.history.length?'<table class="workspace-table"><tr><th>Время</th><th>Операция</th><th>Материал</th><th>Количество</th><th>Основание</th></tr>'+state.history.map(row=>`<tr><td>${esc(new Date(row.time).toLocaleString('ru-RU'))}</td><td>${esc(kindNames[row.kind])}</td><td>${esc(names.get(row.item_id)||row.item_id)}</td><td>${esc(row.quantity)}</td><td>${esc(row.note)}</td></tr>`).join('')+'</table>':'<p>Операций нет.</p>';
  }
  async function stockMove(event){
    event.preventDefault();await action(el('stock-submit'),async()=>{
      const payload={kind:el('stock-kind').value,item_id:el('stock-item').value,order_id:el('stock-order').value,quantity:el('stock-quantity').value,note:el('stock-note').value};
      const signature=JSON.stringify(payload);if(!pendingStock||pendingStock.signature!==signature)pendingStock={signature,request_id:crypto.randomUUID()};
      await api('/api/stock/move',{...payload,request_id:pendingStock.request_id});pendingStock=null;await refreshStock();el('status').textContent='Складская операция сохранена. Цены и суммы сметы не изменены.';notify('Складская операция сохранена.');
    });
  }
  function init(){
    if(ready)return;ready=true;const nav=document.createElement('button');nav.className='nav';nav.dataset.tab='advanced-tools';nav.textContent='Документы';nav.onclick=()=>setTab('advanced-tools');document.querySelector('.sidebar nav').append(nav);titles['advanced-tools']='Документы';
    const section=document.createElement('section');section.id='advanced-tools';section.className='tab-panel';section.hidden=true;
    section.innerHTML=`<p id="advanced-status" role="status"></p><section class="card"><h2>Документы текущей сметы</h2><p>Word — для заказчика; Excel с формулами — внутренняя калькуляция. В Excel можно менять количества, цены и проценты; изменения файла не синхронизируются со сметой.</p><label>Свой шаблон Word до 2 МБ (необязательно)<input id="advanced-template-file" type="file" accept=".docx"></label><div class="prices-actions"><button id="advanced-docx">Смета Word</button><button id="advanced-xlsx">Excel с формулами</button><button id="advanced-template">Скачать шаблон Word</button><button id="advanced-backup">Полная резервная копия ZIP</button></div></section>
      <section class="card"><h2>Склад материалов</h2><p>Количество учитывается в единицах материала из справочника. Для резерва и списания в производство выберите сохранённый заказ. Стоимость запасов и бухгалтерские проводки здесь не рассчитываются.</p><button id="advanced-stock-refresh">Обновить остатки</button><div id="advanced-stock-balances"></div><div id="advanced-stock-reservations"></div><form id="advanced-stock-form"><div class="form-grid"><label>Операция<select id="advanced-stock-kind">${Object.entries(kindNames).map(([value,label])=>`<option value="${value}">${label}</option>`).join('')}</select></label><label>Материал<select id="advanced-stock-item" required></select></label><label>Заказ<select id="advanced-stock-order"></select></label><label>Количество в единицах материала<input id="advanced-stock-quantity" inputmode="decimal" required></label><label class="wide">Основание операции<input id="advanced-stock-note" maxlength="1000" required></label></div><button id="advanced-stock-submit" type="submit" class="primary">Записать операцию</button></form><details><summary>История склада</summary><div id="advanced-stock-history"></div></details></section>
      <section class="card"><h2>Похожие названия материалов</h2><div class="form-grid"><label>Название<input id="advanced-match-query" maxlength="300"></label><label>Единица (необязательно)<input id="advanced-match-unit" maxlength="30"></label></div><button id="advanced-match">Найти совпадения</button><div id="advanced-match-result"></div></section>
      <section class="card"><h2>Ключи сервисов</h2><p>По кнопке ключ сохраняется в системном хранилище macOS или Windows. В заказ, базу смет и резервную копию он не записывается. Можно по-прежнему вводить ключ только на странице поиска.</p><div class="form-grid"><label>Сервис<select id="advanced-key-service"><option value="dadata">DaData</option><option value="tavily">Tavily</option></select></label><label>API-ключ<input id="advanced-key" type="password" autocomplete="off" maxlength="256"></label></div><button id="advanced-key-save">Сохранить в системном хранилище</button> <button id="advanced-key-delete">Удалить сохранённый ключ</button> <button id="advanced-key-status">Проверить наличие ключей</button><p id="advanced-key-result"></p><label class="check"><input id="advanced-use-dadata" type="checkbox">Использовать сохранённый ключ DaData в этом сеансе</label><label class="check"><input id="advanced-use-tavily" type="checkbox">Использовать сохранённый ключ Tavily в этом сеансе</label></section>`;
    document.querySelector('main footer').before(section);
    el('docx').onclick=()=>action(el('docx'),()=>documents('docx'));el('xlsx').onclick=()=>action(el('xlsx'),()=>documents('xlsx'));
    el('template').onclick=()=>action(el('template'),async()=>{const r=await api('/api/docx/template',{});download64(r.content,'Customer_template.docx','application/vnd.openxmlformats-officedocument.wordprocessingml.document');});
    el('backup').onclick=()=>action(el('backup'),async()=>{const r=await api('/api/backup/full',{});download64(r.content,'Estimator_backup_'+new Date().toISOString().slice(0,10)+'.zip','application/zip');el('status').textContent='В копию вошли базы, журнал и исходные документы. Инструкция восстановления находится в архиве.';notify(el('status').textContent);});
    el('stock-form').onsubmit=stockMove;el('stock-refresh').onclick=()=>action(el('stock-refresh'),refreshStock);
    el('match').onclick=()=>action(el('match'),async()=>{const r=await api('/api/catalog/suggest',{query:el('match-query').value,unit:el('match-unit').value});el('match-result').innerHTML='<p>'+esc(r.notice)+'</p>'+r.items.map(item=>`<p>${esc(item.name)} · ${esc(item.unit)} · ${esc(item.article)} · ${esc(item.supplier)} (${item.score}% сходства)</p>`).join('');});
    el('key-save').onclick=()=>action(el('key-save'),async()=>{const service=el('key-service').value;await api('/api/secrets/save',{service,key:el('key').value.trim()});el('key').value='';el('use-'+service).checked=true;el('key-result').textContent='Ключ '+service+' сохранён. Использование включено для этого сеанса.';});
    el('key-delete').onclick=()=>action(el('key-delete'),async()=>{const service=el('key-service').value;await api('/api/secrets/delete',{service});el('use-'+service).checked=false;el('key-result').textContent='Сохранённый ключ удалён.';});
    el('key-status').onclick=()=>action(el('key-status'),async()=>{const r=await api('/api/secrets/status',{});el('key-result').textContent=r.available?Object.entries(r.stored).map(([key,present])=>key+': '+(present?'сохранён':'отсутствует')).join('; '):r.message;});
  }
  document.addEventListener('estimator-ready',init);
})();
