'use strict';
(()=>{
  let guide=null,active='start',query='',started=false;
  const topicFor={'supply-hub':'auto-supply',estimate:'estimate',orders:'orders','advanced-tools':'documents',own:'catalog','price-updates':'prices','price-monitor':'schedule',stock:'stock',production:'production','advanced-geometry':'geometry',compare:'comparison',actual:'actual',catalog:'sources',sources:'sources',search:'connections',assistant:'assistant',settings:'company',connections:'connections',help:'start'};
  const normalize=text=>String(text).toLocaleLowerCase('ru').replaceAll('ё','е');
  const matches=article=>!query||query.split(/\s+/).every(word=>normalize([article.title,article.lead,article.keywords,...article.steps.flatMap(s=>[s.title,s.text]),...article.tips].join(' ')).includes(word));
  const navigateAction=action=>document.dispatchEvent(new CustomEvent('navigate-estimator',{detail:action}));
  function topicHTML(article){return `<span class="section-kicker">${esc(article.category)}</span><h2 tabindex="-1" id="guide-article-title">${esc(article.title)}</h2><p class="guide-lead">${esc(article.lead)}</p><ol class="guide-steps">${article.steps.map((step,index)=>`<li><h3>${esc(step.title)}</h3><p>${esc(step.text)}</p>${step.action?`<button class="guide-action" data-guide-action="${index}">${esc(step.action.label)} <span aria-hidden="true">↗</span></button>`:''}</li>`).join('')}</ol>${article.tips.length?`<aside class="guide-tips"><h3>Полезно знать</h3><ul>${article.tips.map(t=>`<li>${esc(t)}</li>`).join('')}</ul></aside>`:''}`;}
  function render(focus=false){
    const filtered=guide.articles.filter(matches),selected=filtered.find(a=>a.id===active)||filtered[0];if(selected)active=selected.id;
    $('guide-count').textContent=query?(filtered.length?'Найдено тем: '+filtered.length:'Нет тем по этому запросу'):'Выберите тему слева или найдите нужную операцию по слову.';
    $('guide-topics').innerHTML='<p class="guide-toc-label">'+(query?'РЕЗУЛЬТАТЫ ПОИСКА':'СОДЕРЖАНИЕ')+'</p>'+filtered.map(a=>`<button class="guide-topic" data-guide-topic="${a.id}" ${a.id===active?'aria-current="page"':''}><small>${String(guide.articles.indexOf(a)+1).padStart(2,'0')}</small><span>${esc(a.title)}</span></button>`).join('');
    if(!selected){$('guide-content').innerHTML='<div class="guide-no-result"><h3>Попробуйте другое слово</h3><p>Например: «прайс», «ИНН», «сохранить», «раскрой», «Word» или «резервная копия».</p><button id="guide-no-reset" class="guide-action">Показать все темы</button></div>';$('guide-no-reset').onclick=reset;return;}
    const index=guide.articles.indexOf(selected),prev=guide.articles[index-1],next=guide.articles[index+1];
    $('guide-content').innerHTML=topicHTML(selected)+`<div class="guide-pagination">${prev?`<button data-guide-next="${prev.id}">← ${esc(prev.title)}</button>`:'<span></span>'}${next?`<button data-guide-next="${next.id}">${esc(next.title)} →</button>`:''}</div>`;
    if(focus){$('guide-article-title').focus({preventScroll:true});$('guide-content').scrollIntoView?.({block:'start',behavior:'smooth'});}
  }
  function reset(){query='';$('guide-query').value='';render();$('guide-query').focus();}
  function openTopic(id){if(!guide)return;query='';$('guide-query').value='';active=guide.articles.some(a=>a.id===id)?id:'start';render(true);}
  function offlineGuide(){
    const body=guide.articles.map(a=>'<article>'+topicHTML(a).replace(/<button.*?<\/button>/gs,'')+'</article>').join('');
    const html='<!doctype html><html lang="ru"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Инструкция сметчика '+esc(guide.version)+'</title><style>body{max-width:900px;margin:40px auto;padding:0 24px;font:16px/1.7 system-ui,sans-serif;color:#243b2a}h1,h2,h3{line-height:1.35}article{padding:24px 0;border-top:1px solid #cbd8c9}h3{font-size:17px}li{padding-left:8px;margin:20px 0}.section-kicker{font-size:12px;color:#557354}.guide-tips{background:#f1f5ed;padding:12px 24px;border-radius:8px}.guide-tips h3{font-size:14px}.guide-tips li{margin:7px 0}.guide-lead{color:#526d55}@media print{article{break-before:page}button{display:none}}</style><h1>Сметчик: инструкция</h1><p>Версия '+esc(guide.version)+' · обновлено '+esc(guide.updated)+'. Файл можно читать без интернета. Кнопки перехода доступны внутри программы.</p>'+body+'</html>';
    download(html,'Smetchik_instruction_v'+guide.version+'.html','text/html;charset=utf-8');notify('Инструкция подготовлена. Сохраните HTML и открывайте его без программы.');
  }
  async function init(){if(started)return;started=true;try{const response=await fetch('/guide.json');if(!response.ok)throw Error('Файл инструкции недоступен. Распакуйте архив полностью.');guide=await response.json();
      $('help').innerHTML=`<div class="guide-header"><div><span class="guide-version">Руководство ${esc(guide.version)} · обновлено ${esc(guide.updated)}</span><h2>От первого заказа до готовой сметы</h2><p>Выберите задачу — пройдём её по шагам. Кнопки в инструкции открывают нужный раздел программы.</p></div><button id="guide-download">Скачать инструкцию</button></div>${guide.version!==boot.version?'<p class="guide-callout" role="alert">Версия инструкции не совпадает с программой. Распакуйте полный комплект одной версии.</p>':''}<div class="guide-search-box"><label>Что вы хотите сделать?<input id="guide-query" type="search" placeholder="Например: обновить цены, внести ИНН, сохранить PDF…" autocomplete="off"></label><button id="guide-reset" aria-label="Очистить поиск инструкции">×</button></div><p id="guide-count" class="guide-search-status" role="status"></p><div class="guide-layout"><nav id="guide-topics" class="guide-toc" aria-label="Темы инструкции"></nav><article id="guide-content" class="card guide-article"></article></div>`;
      $('guide-query').addEventListener('input',e=>{query=normalize(e.target.value.trim());render();});$('guide-reset').onclick=reset;$('guide-download').onclick=offlineGuide;
      $('guide-topics').onclick=e=>{const b=e.target.closest('[data-guide-topic]');if(b){active=b.dataset.guideTopic;render(true);}};
      $('guide-content').onclick=e=>{const b=e.target.closest('[data-guide-action],[data-guide-next]');if(!b)return;if(b.dataset.guideNext)openTopic(b.dataset.guideNext);else{const article=guide.articles.find(a=>a.id===active),step=article.steps[Number(b.dataset.guideAction)];navigateAction(step.action);}};
      render();document.dispatchEvent(new CustomEvent('estimator-guide-ready'));
    }catch(error){$('help').innerHTML='<div class="card"><h2>Не удалось открыть инструкцию</h2><p>'+esc(error.message)+'</p><p>В папке docs есть USER_GUIDE.md. Распакуйте программу заново в отдельную папку.</p></div>';}}
  document.addEventListener('open-guide',e=>{document.querySelector('.nav[data-tab=help]').click();if(guide)openTopic(e.detail.topic||topicFor[e.detail.tab]||'start');});
  document.addEventListener('estimator-interface-ready',init);if(document.querySelector('#navigation-search'))init();
})();
