'use strict';
(()=>{
let latest=null, chosen=null;
const hubApi=(action,body={})=>api('/api/hub/'+action,body);
const moment=value=>value?new Date(value*1000).toLocaleString('ru-RU'):'ещё не было';
const field=(name,label,placeholder='',value='')=>`<label>${esc(label)}<input name="${name}" placeholder="${esc(placeholder)}" value="${esc(value)}" required></label>`;
const sourceForm=`<form id="hub-source-form" class="card hub-form"><h3>Подключить автопрайс</h3>${field('name','Поставщик','Название компании')}${field('url','Прямая ссылка на прайс','https://…')}<label>Формат<select name="format"><option value="json">JSON</option><option value="csv">CSV · разделитель ;</option></select></label><label class="check"><input name="enabled" type="checkbox" checked> Проверять раз в 24 часа</label><p class="muted">Нужны артикулы, ключи материалов, наличие и остатки. Обычная страница каталога для этого формата не подходит.</p><div class="row-tools"><button class="primary">Подключить</button><button type="button" id="hub-example">Скачать образец прайса</button></div></form>`;
async function refresh(){latest=await hubApi('status');render();}
function render(){
 $('hub-status').textContent=latest.running?(boot.hosted?'Ежедневные проверки работают на сервере, даже когда браузер закрыт.':'Проверки работают, пока программа открыта и компьютер не спит.'):'Расписание запускается при подключении источника.';
 $('hub-sources').innerHTML=latest.sources.length?latest.sources.map(s=>`<article class="hub-source"><div><strong>${esc(s.name)}</strong><p>${s.kind==='supplier'?'Прайс поставщика':'Маршрут доставки'} · ${s.enabled?'каждые 24 часа':'по запросу'}</p><p>Последний успех: ${esc(moment(s.last_success))}<br>Состояние: ${s.fresh?'доступен для подбора':s.last_status==='error'?'ошибка — исключён из подбора':'нужна проверка'} · следующая: ${s.enabled?esc(moment(s.next_due)):'вручную'}</p>${s.kind==='delivery'&&s.fresh?`<p><b>${money(s.snapshot[0]?.price)} ₽</b> · ${esc(s.snapshot[0]?.provider)} · ${esc(s.snapshot[0]?.name)}</p><button type="button" data-delivery="${esc(s.id)}">Добавить доставку в смету</button>`:''}</div><div class="row-tools"><button type="button" data-check="${esc(s.id)}">Проверить сейчас</button><button type="button" data-toggle="${esc(s.id)}">${s.enabled?'Остановить расписание':'Включить расписание'}</button><button type="button" data-remove="${esc(s.id)}">Удалить</button></div></article>`).join(''):'<p class="muted">Источники ещё не подключены. Добавьте прайс поставщика или маршрут доставки.</p>';
 $('hub-history').innerHTML=latest.history.slice(0,20).map(h=>`<li>${esc(moment(h.checked))} · ${h.status==='ok'?'Обновлено':'Ошибка'} · ${esc(latest.sources.find(s=>s.id===h.source_id)?.name||'Удалённый источник')}: ${esc(h.summary)}</li>`).join('')||'<li>Проверок пока нет.</li>';
}
async function guardedHub(button,action){button.disabled=true;try{await action();}catch(e){notify(e.message,true);}finally{button.disabled=false;}}
function addRow(row){project.rows.push({...newRow(),...row});markDirty();renderRows();scheduleCalculate(0);setTab('estimate');notify('Позиция добавлена в открытую смету. Проверьте условия и сохраните заказ.');}
function init(){
 if($('supply-hub'))return;
 titles['supply-hub']='Автоподбор и доставка';
 const section=document.createElement('section');section.id='supply-hub';section.className='tab-panel';section.hidden=true;
 section.innerHTML=`<div class="intro"><h2>Автоподбор и доставка</h2><p>Сначала подключите прайсы с наличием. Затем укажите нужный материал — программа выберет доступное предложение с минимальной стоимостью закупки.</p></div><p id="hub-status" class="hub-callout"></p><div class="hub-grid"><form id="hub-select-form" class="card hub-form"><h3>Подобрать материал</h3>${field('material_key','Ключ взаимозаменяемого материала','Например: PVC-WHITE-3-2030x3050')}${field('unit','Единица цены','лист')}${field('quantity','Нужное количество','','1')}<label>Налоговый состав<select name="tax_basis"><option value="vat_included">Цена включает НДС</option><option value="no_vat">Поставщик без НДС</option></select></label><button class="primary">Подобрать из наличия</button><div id="hub-selection" aria-live="polite"></div></form>${sourceForm}</div><details class="card"><summary>Добавить маршрут доставки · ApiShip</summary><form id="hub-delivery-form" class="hub-form"><p>Рассчитывается доставка до двери. Адреса, вес и габариты отправляются в ApiShip. Нужен ключ в настройках сервера и договоры с перевозчиками.</p>${field('name','Название маршрута','Поставщик → мастерская')}${field('from_address','Полный адрес отправления')}${field('to_address','Полный адрес доставки')}<div class="hub-grid">${field('weight_g','Вес, граммы','','1000')}${field('length_cm','Длина, см','','30')}${field('width_cm','Ширина, см','','20')}${field('height_cm','Высота, см','','10')}</div>${field('assessed_cost','Объявленная стоимость, ₽','','0')}${field('providers','Коды перевозчиков через запятую','','cdek')}<label>Откуда забирают<select name="pickup_type"><option value="1">От двери отправителя</option><option value="2">Со склада перевозчика</option></select></label><button class="primary">Сохранить и проверять ежедневно</button></form></details><section class="card"><div class="row-tools"><h3>Подключённые источники</h3><button id="hub-refresh-view">Обновить список</button></div><div id="hub-sources"></div></section><details class="card"><summary>Журнал последних проверок</summary><ol id="hub-history"></ol></details>`;
 document.querySelector('main footer').before(section);
 const nav=document.createElement('button');nav.className='nav';nav.dataset.tab='supply-hub';nav.textContent='Автоподбор и доставка';nav.onclick=()=>{setTab('supply-hub');guardedHub(nav,refresh);};document.querySelector('.sidebar nav').append(nav);
 $('hub-refresh-view').onclick=e=>guardedHub(e.currentTarget,refresh);
 $('hub-source-form').onsubmit=e=>{e.preventDefault();const form=e.target,values=Object.fromEntries(new FormData(form));guardedHub(form.querySelector('button'),async()=>{await hubApi('save',{kind:'supplier',name:values.name,enabled:form.elements.enabled.checked,config:{url:values.url,format:values.format}});form.reset();await refresh();notify('Источник сохранён. Первая проверка начнётся в течение минуты.');});};
 $('hub-example').onclick=()=>download(JSON.stringify([{name:'Учебный ПВХ белый 3 мм 2030×3050',article:'DEMO-PVC-3',material_key:'PVC-WHITE-3-2030x3050',unit:'лист',price:'1200',currency:'RUB',tax_basis:'vat_included',available:true,available_quantity:'20',minimum_quantity:'1',package_step:'1'}],null,2),'supplier_feed_EXAMPLE.json','application/json');
 $('hub-delivery-form').onsubmit=e=>{e.preventDefault();const form=e.target,v=Object.fromEntries(new FormData(form));guardedHub(form.querySelector('button'),async()=>{const name=v.name;delete v.name;v.pickup_type=Number(v.pickup_type);v.providers=v.providers.split(',').map(s=>s.trim()).filter(Boolean);await hubApi('save',{kind:'delivery',name,enabled:true,config:v});await refresh();notify('Маршрут сохранён. Тарифы будут обновляться раз в 24 часа.');});};
 $('hub-select-form').onsubmit=e=>{e.preventDefault();chosen=null;const form=e.target;guardedHub(form.querySelector('button'),async()=>{const value=await hubApi('select',Object.fromEntries(new FormData(form)));chosen=value.selected;$('hub-selection').innerHTML=chosen?`<h3>${esc(chosen.name)}</h3><p>${esc(chosen.supplier)} · артикул ${esc(chosen.article)}<br>Купить ${esc(chosen.purchase_quantity)} ${esc(chosen.unit)} × ${money(chosen.price)} ₽</p><p class="hub-total">${money(chosen.total)} ₽</p><p>${esc(value.notice)}</p><button type="button" id="hub-add-selected">Добавить выбранную позицию</button><details><summary>Другие доступные предложения: ${value.alternatives.length-1}</summary><ul>${value.alternatives.slice(1).map(a=>`<li>${esc(a.supplier)} · ${esc(a.article)} · ${money(a.total)} ₽</li>`).join('')}</ul></details>`:'<p>Доступных предложений нет. Проверьте ключ материала, единицу, налоговый состав, остаток и дату последнего успешного обновления.</p>';if(chosen)$('hub-add-selected').onclick=e=>guardedHub(e.currentTarget,async()=>{const targetProject=project;const current=await hubApi('select',Object.fromEntries(new FormData(form)));if(project!==targetProject)throw Error('Открыт другой заказ. Повторите подбор для него.');if(!current.selected||current.selected.source_id!==chosen.source_id||current.selected.article!==chosen.article||current.selected.price!==chosen.price||current.selected.purchase_quantity!==chosen.purchase_quantity)throw Error('Предложение изменилось. Выполните подбор ещё раз.');const c=current.selected;addRow({name:c.name,unit:c.unit,quantity:c.purchase_quantity,price:c.price,increment:c.package_step,source:c.source_url||c.supplier,source_status:'published_snapshot',note:`${c.supplier}; артикул ${c.article}; запрошено ${c.requested_quantity}; ${c.tax_basis==='vat_included'?'НДС включён':'без НДС'}; проверено ${moment(c.checked_at)}`});chosen=null;$('hub-selection').replaceChildren();});});};
 $('hub-sources').onclick=e=>{const b=e.target.closest('button');if(!b)return;guardedHub(b,async()=>{const id=b.dataset.check||b.dataset.remove||b.dataset.toggle||b.dataset.delivery;const s=latest.sources.find(s=>s.id===id);if(b.dataset.check){const r=await hubApi('refresh',{id});notify(r.summary,r.status!=='ok');}else if(b.dataset.remove){if(!confirm('Удалить подключение? Сохранённые сметы останутся.'))return;await hubApi('delete',{id});}else if(b.dataset.toggle){await hubApi('save',{id,kind:s.kind,name:s.name,config:s.config,enabled:!s.enabled});}else{await refresh();const source=latest.sources.find(s=>s.id===id);if(!source?.fresh)throw Error('Тариф устарел. Проверьте маршрут заново.');const q=source.snapshot[0];addRow({name:'Доставка · '+source.name,category:'delivery',quantity:'1',unit:'рейс',price:q.price,source:'ApiShip · '+q.provider+' · '+q.name,source_status:'published_snapshot',note:'Для сохранённых адресов, веса и габаритов; проверено '+moment(source.last_success)});}await refresh();});};
 if(boot.hosted){$('top-order-save').title='Сохранить на сервере · Ctrl / ⌘ + S';$('quit').textContent='Выйти из аккаунта';$('quit').addEventListener('click',async e=>{e.preventDefault();e.stopImmediatePropagation();if(dirty&&!confirm('Есть несохранённые изменения. Выйти?'))return;try{await api('/auth/logout',{});dirty=false;location.assign('/');}catch(error){notify(error.message,true);}},true);document.querySelectorAll('.status-dot').forEach(el=>el.title='Проекты хранятся на сервере');}
}
document.addEventListener('estimator-ready',init);if(typeof boot!=='undefined'&&boot)init();
})();
