'use strict';
(() => {
let initialized=false, currentOrder=null, catalogEdit=null, offerEdit=null, profileRecord=null, profile={}, draftRecord=null;
let ownItems=[], orders=[], offers=[], variants=[], templateItems=[], importBook=null, importChanges=[], importFile='', draftTimer, draftSaving=false, draftPending=false;
const ws=(action,body={})=>api('/api/workspace/'+action,body);
const field=(form,name)=>form.elements.namedItem(name);
const formData=form=>Object.fromEntries(Array.from(form.elements).filter(e=>e.name).map(e=>[e.name,e.type==='checkbox'?e.checked:e.value.trim()]));
const fill=(form,data)=>{form.reset();for(const [k,v]of Object.entries(data||{})){const e=field(form,k);if(e){if(e.type==='checkbox')e.checked=!!v;else e.value=v??'';}}};
const snapshot=()=>{collectForm();return structuredClone(project);};
function extras(){project.extensions??={};project.extensions.actuals??={};project.extensions.extra_actual??='';project.extensions.extra_note??='';return project.extensions;}
async function guarded(button,callback){if(button.disabled)return;button.disabled=true;try{return await callback();}catch(e){notify(e.message,true);}finally{button.disabled=false;}}
function bytes64(file){return file.arrayBuffer().then(buffer=>{const bytes=new Uint8Array(buffer);let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(text);});}
function download64(content,name,type){const bytes=Uint8Array.from(atob(content),c=>c.charCodeAt(0));download(bytes,name,type);}
function actionButtons(kind,id,items){return items.map(([action,label])=>`<button data-${kind}-action="${action}" data-id="${esc(id)}">${label}</button>`).join('');}
function addMarkup(){
  const sections=[['own','Мои материалы'],['orders','Заказы и версии'],['production','Шаблоны и производство'],['compare','Варианты и поставщики'],['actual','План и факт'],['assistant','Помощник'],['settings','Моя компания']];
  sections.forEach(([id,title])=>{titles[id]=title;const button=document.createElement('button');button.className='nav';button.dataset.tab=id;button.textContent=title;document.querySelector('.sidebar nav').append(button);button.addEventListener('click',()=>{setTab(id);refreshTab(id).catch(e=>notify(e.message,true));});});
  const container=document.createElement('div');container.innerHTML=`
  <section id="own" class="tab-panel" hidden><div class="intro"><h2>Собственный справочник</h2><p>Ваши материалы и расценки хранятся на этом компьютере. При добавлении в заказ уточняйте нужное количество и применимость цены.</p></div>
    <div class="workspace-toolbar"><input id="own-query" type="search" placeholder="Название, поставщик, артикул"><button id="own-new" class="primary">Добавить материал или работу</button><button id="own-import">Импорт прайса XLSX</button></div><div id="own-list" class="workspace-list"></div>
    <section id="xlsx-panel" class="card" hidden><h2>Импорт Excel с проверкой изменений</h2><p class="muted">До 8 МБ и 500 импортируемых позиций. Выберите столбцы. Цены с формулами предварительно сохраните в Excel как значения.</p><input id="xlsx-file" type="file" accept=".xlsx"><div id="xlsx-options" hidden><div class="form-grid"><label>Лист<select id="xlsx-sheet"></select></label><label>Начать с видимой строки №<input id="xlsx-start" value="2" inputmode="numeric"></label><label>Поставщик по умолчанию<input id="xlsx-supplier"></label><label>Дата прайса<input id="xlsx-date" type="date"></label></div><div id="xlsx-mapping" class="form-grid"></div><div id="xlsx-sample" class="table-wrap"></div><button id="xlsx-preview">Проверить импорт</button><div id="xlsx-changes"></div><button id="xlsx-apply" class="primary" disabled>Сохранить проверенные изменения</button></div></section>
  </section>
  <section id="orders" class="tab-panel" hidden><div class="intro"><h2>Заказы на этом компьютере</h2><p>Каждое сохранение существующего заказа создаёт версию. JSON-файлы по-прежнему можно переносить между компьютерами.</p></div>
    <div class="workspace-toolbar"><input id="orders-query" type="search" placeholder="Название или заказчик"><button id="order-save" class="primary">Сохранить текущий заказ в каталог</button><button id="backup-save">Резервная копия базы</button><button id="backup-open">Загрузить копию базы</button></div>
    <div class="card"><label class="check"><input id="autosave-draft" type="checkbox"> Сохранять черновик на этом компьютере при изменении сметы</label><p id="draft-status" class="muted"></p><button id="draft-recover" hidden>Восстановить последний черновик</button></div><div id="orders-list" class="workspace-list"></div><div id="order-versions" class="card" hidden></div>
  </section>
  <section id="production" class="tab-panel" hidden><div class="intro"><h2>Шаблоны и производственные нормы</h2><p>Шаблон рассчитывает известный расход. Цены и недостающие технологические параметры заполняются отдельно.</p></div>
    <div class="workspace-columns"><form id="template-form" class="card"><h2>Новая смета по типу изделия</h2><div class="form-grid">
    <label class="wide">Изделие<select name="kind"><option value="banner">Баннер</option><option value="sign">Таблички ПВХ</option><option value="lightbox">Световой короб</option><option value="letters">Объёмные буквы</option><option value="cards">Визитки</option></select></label>
    <label>Количество готовых изделий / комплектов<input name="quantity" value="1" required inputmode="numeric"></label><label>Запас материала / бумаги, %<input name="waste_percent" value="0" inputmode="decimal"></label>
    <label>Ширина изделия, мм<input name="width_mm" inputmode="decimal"></label><label>Высота изделия, мм<input name="height_mm" inputmode="decimal"></label>
    <label>Ширина листа, мм · для ПВХ и визиток<input name="sheet_width_mm" inputmode="decimal"></label><label>Высота листа, мм<input name="sheet_height_mm" inputmode="decimal"></label>
    <label>Отступ от края листа, мм<input name="edge_mm" value="0" inputmode="decimal"></label><label>Зазор между деталями, мм<input name="gap_mm" value="0" inputmode="decimal"></label>
    <label>Вылет визитки на сторону, мм<input name="bleed_mm" value="0" inputmode="decimal"></label><label>Стороны печати визиток<select name="sides"><option value="1">Одна</option><option value="2">Две</option></select></label>
    <label class="check"><input name="laminate" type="checkbox"> Ламинация</label><label class="check"><input name="delivery" type="checkbox"> Доставка</label><label class="check"><input name="installation" type="checkbox"> Монтаж</label></div><p class="fine">Раскрой регулярный, с поворотом. Для объёмных букв расход по контурам и электрические комплектующие остаются для расчёта специалистом. Если материал включён в печать, скорректируйте отдельные строки.</p><button class="primary" type="submit">Создать черновик сметы</button></form>
    <div><form id="operation-form" class="card"><h2>Стоимость производственной операции</h2><div class="form-grid"><label class="wide">Операция<input name="name" required placeholder="Печать, фрезеровка, работа сборщика"></label><label>Объём, единиц<input name="quantity" value="1" inputmode="decimal" required></label><label>Подготовка, минут<input name="setup_minutes" value="0" inputmode="decimal" required></label><label>Минут на единицу<input name="minutes_per_unit" inputmode="decimal" required></label><label>Ставка часа, ₽<input name="hourly_rate" inputmode="decimal" placeholder="Пусто = неизвестна"></label></div><p class="fine">Часы = (подготовка + объём × минут на единицу) / 60. Введите свою ставку и проверьте, включает ли она труд, оборудование и расходники.</p><button class="primary" type="submit">Рассчитать и добавить в смету</button></form>
    <section class="card"><h2>Собственные шаблоны</h2><p class="muted">Сохраняют состав текущего заказа и его значения. При повторном использовании пересмотрите количества и цены.</p><button id="template-save">Сохранить текущую смету как шаблон</button><div id="templates-list"></div></section></div></div>
  </section>
  <section id="compare" class="tab-panel" hidden><div class="intro"><h2>Варианты заказа и предложения поставщиков</h2><p>Сохраняйте разные сметы и сравнивайте их результаты. Количество строк каждого варианта проверяется отдельно.</p></div>
    <section class="card"><div class="workspace-toolbar"><button id="variant-save" class="primary">Сохранить текущий вариант</button><button id="variants-calculate">Сравнить отмеченные варианты</button></div><div id="variants-list"></div><div id="variants-result" class="table-wrap"></div></section>
    <section class="card"><h2>Предложения поставщиков</h2><form id="offer-form"><div class="form-grid"><label>Поставщик<input name="supplier" required></label><label>Материал / артикул<input name="item" required></label><label>Единица<input name="unit" value="лист" required></label><label>Цена за единицу, ₽<input name="price" inputmode="decimal"></label><label>Доставка всего, ₽<input name="delivery" inputmode="decimal" placeholder="0, если включена"></label><label>Кратность закупки<input name="increment" inputmode="decimal" placeholder="Пусто = без округления"></label><label>Минимальная оплата, ₽<input name="minimum" inputmode="decimal" placeholder="0, если нет"></label><label>Дата предложения<input name="date" type="date"></label><label class="wide">Источник<input name="source"></label><label class="wide">Условия и характеристики<textarea name="terms" rows="2"></textarea></label><label class="wide check"><input name="comparable" type="checkbox"> Характеристики, состав цены и налоговая база проверены как сопоставимые</label></div><button class="primary" type="submit">Сохранить предложение</button><button id="offer-clear" type="button">Новая запись</button></form><div id="offers-list" class="workspace-list"></div>
    <div class="workspace-toolbar"><label>Нужное количество<input id="offer-quantity" value="1" inputmode="decimal"></label><label>Единица<input id="offer-unit" value="лист"></label><button id="offers-calculate">Сравнить отмеченные предложения</button></div><div id="offers-result" class="table-wrap"></div></section>
  </section>
  <section id="actual" class="tab-panel" hidden><div class="intro"><h2>Плановые и фактические прямые затраты</h2><p>Введите реально понесённые расходы. Пустая сумма означает, что фактические затраты ещё не внесены.</p></div><section class="card"><div id="actual-table" class="table-wrap"></div><div class="form-grid"><label>Дополнительные расходы вне строк сметы, ₽<input id="actual-extra" inputmode="decimal" placeholder="0, если расходов не было"></label><label>Что за расходы<input id="actual-extra-note"></label></div><button id="actual-calculate" class="primary">Сравнить план и факт</button><div id="actual-result"></div></section></section>
  <section id="assistant" class="tab-panel" hidden><div class="intro"><h2>Помощник для черновика сметы</h2><p>Извлекает тип изделия, размеры и количество из текста. Перед созданием сметы проверьте параметры.</p></div><form id="assistant-form" class="card"><label>Задание<textarea name="text" rows="4" maxlength="10000" required placeholder="Нужно 20 табличек ПВХ 600 × 400 мм с печатью и монтажом"></textarea></label><label class="check"><input name="use_ai" type="checkbox"> Использовать установленную локальную модель Ollama</label><div class="workspace-toolbar"><select name="model" id="ollama-model"><option value="">Сначала получите список моделей</option></select><button id="ollama-refresh" type="button">Найти локальные модели</button></div><p class="fine">Без Ollama работает разбор по правилам. ИИ-режим обращается к Ollama на этом компьютере; модель устанавливается отдельно. История диалога и API-ключи в базу программы не записываются.</p><button class="primary" type="submit">Разобрать задание</button><div id="assistant-result"></div></form></section>
  <section id="settings" class="tab-panel" hidden><div class="intro"><h2>Реквизиты и оформление документов</h2><p>Данные используются при выгрузке PDF и Excel. Заполняйте только сведения своей компании.</p></div><form id="profile-form" class="card"><div class="form-grid"><label class="wide">Компания<input name="company"></label><label class="wide">Реквизиты<textarea name="details" rows="3" maxlength="4000"></textarea></label><label class="wide">Контакты<input name="contacts" maxlength="4000"></label><label class="wide">Условия по умолчанию<textarea name="terms" rows="3" maxlength="4000"></textarea></label><label class="wide">Логотип для PDF и Excel, PNG/JPEG до 1 МБ<input id="company-logo" type="file" accept="image/png,image/jpeg"></label></div><p id="logo-status" class="muted"></p><button id="logo-clear" type="button">Убрать логотип</button><button type="submit" class="primary">Сохранить реквизиты</button></form></section>
  <dialog id="own-dialog"><form id="own-form"><div class="dialog-head"><h2>Собственная расценка</h2><button id="own-close" type="button" aria-label="Закрыть">×</button></div><div class="form-grid"><label class="wide">Название<input name="name" required maxlength="300"></label><label>Поставщик<input name="supplier" maxlength="300"></label><label>Артикул<input name="article" maxlength="100"></label><label>Категория<select name="category"><option value="material">Материал</option><option value="work">Работа</option><option value="service">Услуга</option><option value="delivery">Доставка</option></select></label><label>Единица<input name="unit" value="шт." list="units" required></label><label>Цена, ₽<input name="price" inputmode="decimal"></label><label>Кратность закупки<input name="increment" inputmode="decimal"></label><label>Минимальная оплата, ₽<input name="minimum_charge" value="0" inputmode="decimal"></label><label>Дата цены<input name="price_date" type="date"></label><label class="wide">Источник<input name="source" maxlength="2000"></label><label class="wide">Условия<textarea name="note" rows="3" maxlength="10000"></textarea></label></div><div id="own-error" class="error-box" hidden></div><button class="primary" type="submit">Сохранить в справочник</button></form></dialog>
  <input id="backup-file" type="file" accept=".json" hidden>`;
  document.querySelector('main').insertBefore(container,document.querySelector('footer'));
  const save=document.createElement('button');save.id='top-order-save';save.textContent='В каталог заказов';document.querySelector('.top-actions').append(save);
  const exportButtons=document.createElement('div');exportButtons.className='workspace-export';exportButtons.innerHTML='<button id="pdf-client" class="primary">Смета PDF</button><button id="xlsx-client">Смета Excel</button><button id="pdf-internal">Калькуляция PDF</button><button id="xlsx-internal">Калькуляция Excel</button>';document.querySelector('.report-buttons').append(exportButtons);
}
async function refreshTab(tab){if(tab==='own')await refreshCatalog();if(tab==='orders')await refreshOrders();if(tab==='production')await refreshTemplates();if(tab==='compare'){await refreshVariants();await refreshOffers();}if(tab==='actual')renderActual();}
async function refreshCatalog(){const data=await ws('list',{kind:'catalog',query:$('own-query').value});ownItems=data.items;$('own-list').innerHTML=ownItems.map(item=>`<article class="card compact-card"><div><h3>${esc(item.name)}</h3><p>${money(item.data.price)} ₽ / ${esc(item.data.unit)} · ${esc(item.data.supplier||'Свой тариф')}</p><p class="muted">Артикул: ${esc(item.data.article||'—')} · дата: ${esc(item.data.price_date||'не указана')}</p></div><div class="row-tools">${actionButtons('own',item.id,[['use','В смету'],['edit','Изменить'],...(item.data.price_observation?.document?[['source-document','Исходный прайс']]:[]),['delete','Удалить']])}</div></article>`).join('')||'<p class="empty">Справочник пока пуст. Добавьте расценку или сохраните позицию из сметы кнопкой «В справочник».</p>';}
function editCatalog(item,data){catalogEdit=item;fill($('own-form'),data||item?.data||{unit:'шт.',minimum_charge:'0',category:'material'});$('own-error').hidden=true;$('own-dialog').showModal();}
async function saveCatalog(event){event.preventDefault();const form=$('own-form');await guarded(form.querySelector('[type=submit]'),async()=>{const data={...formData(form),quantity:'1',confirmed:false,source_status:'manual'};for(const key of ['price','increment','minimum_charge'])data[key]=decimalInput(data[key]);try{await ws('save',{kind:'catalog',name:data.name,data,id:catalogEdit?.id,expected_revision:catalogEdit?.revision});$('own-dialog').close();await refreshCatalog();notify('Расценка сохранена в собственный справочник.');}catch(e){$('own-error').textContent=e.message;$('own-error').hidden=false;}});}
async function saveOrder(){const data=snapshot(), original=project, stamp=sequence;const name=data.project.title||prompt('Название заказа');if(!name)return;const record=await ws('save',{kind:'order',name,data,id:currentOrder?.id,expected_revision:currentOrder?.revision});if(project===original){currentOrder=record;if(sequence===stamp)dirty=false;}if(project===original&&!dirty)$('project-hint').textContent='Сохранено на этом компьютере · версия '+record.revision;notify('Заказ сохранён на этом компьютере. Версия '+record.revision+'.');document.dispatchEvent(new CustomEvent('estimate-saved'));await refreshOrders();}
async function refreshOrders(){orders=(await ws('list',{kind:'order',query:$('orders-query').value})).items;$('orders-list').innerHTML=orders.map(item=>`<article class="card compact-card"><h3>${esc(item.name)}</h3><p class="muted">${esc(item.data.project.client||'Заказчик не указан')} · версия ${item.revision} · ${esc(item.updated.slice(0,16).replace('T',' '))} UTC</p><div class="row-tools">${actionButtons('order',item.id,[['open','Открыть'],['copy','Создать копию'],['versions','История'],['delete','Удалить']])}</div></article>`).join('')||'<p class="empty">Сохранённых заказов нет.</p>';}
async function loadStored(kind,id,revision,copy=false){if(!okayReplace())return;const original=project,record=await ws('get',{kind,id,revision});const latest=kind==='order'&&!copy?(revision?await ws('get',{kind,id}):record):null;if(project!==original)throw Error('Текущий заказ изменился. Повторите открытие.');loadProject(record.data,(copy?'Копия: ':'Открыто: ')+record.name);currentOrder=latest;if(revision||copy)markDirty();if(revision)$('project-hint').textContent='Восстановлена версия '+revision+'. Следующее сохранение создаст новую версию.';setTab('estimate');}
async function saveNamed(kind,label){const data=snapshot(),name=prompt(label,data.project.title||'Новая смета');if(!name)return;await ws('save',{kind,name,data});notify('Сохранено: '+name);if(kind==='template')await refreshTemplates();else await refreshVariants();}
async function refreshTemplates(){templateItems=(await ws('list',{kind:'template'})).items;$('templates-list').innerHTML=templateItems.map(item=>`<div class="saved-item"><span>${esc(item.name)}</span>${actionButtons('template',item.id,[['use','Использовать'],['delete','Удалить']])}</div>`).join('')||'<p class="muted">Собственных шаблонов пока нет.</p>';}
async function refreshVariants(){variants=(await ws('list',{kind:'variant'})).items;$('variants-list').innerHTML=variants.map(item=>`<div class="saved-item"><label class="check"><input type="checkbox" data-variant-check="${esc(item.id)}"> ${esc(item.name)}</label>${actionButtons('variant',item.id,[['open','Открыть копию'],['delete','Удалить']])}</div>`).join('')||'<p class="muted">Сохраните несколько вариантов текущей сметы.</p>';}
async function compareVariants(){const ids=Array.from(document.querySelectorAll('[data-variant-check]:checked')).map(e=>e.dataset.variantCheck);if(ids.length<2||ids.length>20)throw Error('Отметьте от 2 до 20 вариантов.');const selected=variants.filter(x=>ids.includes(x.id));const out=[];for(const item of selected){out.push({item,result:await api('/api/calculate',item.data)});}$('variants-result').innerHTML='<table class="workspace-table"><tr><th>Вариант</th><th>Тираж</th><th>Себестоимость</th><th>Цена заказа</th><th>За изделие</th><th>Прибыль</th><th>Статус</th></tr>'+out.map(({item,result:r})=>`<tr><td>${esc(item.name)}</td><td>${esc(item.data.project.quantity)}</td><td>${money(r.totals.cost)}</td><td>${money(r.totals.total)}</td><td>${money(r.totals.unit_total)}</td><td>${money(r.totals.profit)}</td><td>${esc(r.status)}</td></tr>`).join('')+'</table>';}
async function refreshOffers(){offers=(await ws('list',{kind:'offer'})).items;$('offers-list').innerHTML=offers.map(item=>`<div class="saved-item"><label class="check"><input type="checkbox" data-offer-check="${esc(item.id)}"> ${esc(item.data.supplier)} · ${esc(item.data.item)} · ${money(item.data.price)} ₽/${esc(item.data.unit)}</label>${actionButtons('offer',item.id,[['edit','Изменить'],['delete','Удалить']])}</div>`).join('');}
async function compareOffers(){const ids=Array.from(document.querySelectorAll('[data-offer-check]:checked')).map(e=>e.dataset.offerCheck);if(ids.length<2)throw Error('Отметьте минимум два предложения.');const r=await api('/api/compare-offers',{quantity:decimalInput($('offer-quantity').value),unit:$('offer-unit').value,offers:offers.filter(x=>ids.includes(x.id)).map(x=>x.data)});$('offers-result').innerHTML='<table class="workspace-table"><tr><th>Поставщик</th><th>К закупке</th><th>С доставкой, ₽</th><th>Проверка</th></tr>'+r.offers.map(x=>`<tr class="${x.best?'best-offer':''}"><td>${esc(x.supplier)}</td><td>${esc(x.billed_quantity)} ${esc(x.unit)}</td><td>${money(x.total)}</td><td>${x.best?'Наименьшая сумма среди подтверждённых':x.eligible?'Сопоставимое предложение':esc(x.missing.join('; '))}</td></tr>`).join('')+'</table>';}
function renderActual(){const e=extras();$('actual-table').innerHTML='<table class="workspace-table"><tr><th>Позиция</th><th>Фактические прямые расходы, ₽</th><th>Основание / примечание</th></tr>'+project.rows.map(row=>`<tr><td>${esc(row.name)}</td><td><input data-actual-id="${esc(row.id)}" data-key="amount" inputmode="decimal" value="${esc(e.actuals[row.id]?.amount||'')}" placeholder="Не внесено"></td><td><input data-actual-id="${esc(row.id)}" data-key="note" value="${esc(e.actuals[row.id]?.note||'')}" maxlength="2000"></td></tr>`).join('')+'</table>';$('actual-extra').value=e.extra_actual;$('actual-extra-note').value=e.extra_note;$('actual-result').innerHTML='';}
async function calculateActual(){const r=await api('/api/actuals',snapshot());$('actual-result').innerHTML='<table class="workspace-table"><tr><th>Позиция</th><th>План</th><th>Факт</th><th>Факт минус план</th></tr>'+r.rows.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.planned)}</td><td>${money(x.actual)}</td><td>${money(x.difference)}</td></tr>`).join('')+'</table>'+`<p>Внесённые фактические расходы: <strong>${money(r.known_actual)} ₽</strong>. Отклонение от плана: <strong>${money(r.difference)}</strong>.</p><p class="muted">${r.complete?'Все прямые расходы заполнены. Положительное отклонение означает перерасход.':'Для полного сравнения заполните все фактические суммы и расходы вне сметы, включая явный 0 при их отсутствии.'}</p>`;}
async function readExcel(){const file=$('xlsx-file').files[0];if(!file)return;if(file.size>8388608)throw Error('XLSX должен быть не больше 8 МБ.');importFile=file.name;const content=await bytes64(file);importBook={content};await readSheet(0);}
async function readSheet(index){const data=await api('/api/xlsx/read',{content:importBook.content,sheet:index});Object.assign(importBook,data);$('xlsx-options').hidden=false;$('xlsx-sheet').innerHTML=data.sheets.map((s,i)=>`<option value="${i}">${esc(s.name)}${s.hidden?' (скрыт)':''}</option>`).join('');$('xlsx-sheet').value=String(index);const headers=data.rows[0]?.values||[];const cols=Math.max(headers.length,...data.rows.slice(0,30).map(r=>r.values.length),1);const labels={name:'Название',unit:'Единица',price:'Цена',supplier:'Поставщик',article:'Артикул',source:'Источник',note:'Примечание'};$('xlsx-mapping').innerHTML=Object.entries(labels).map(([key,label])=>`<label>${label}<select data-map="${key}"><option value="-1">Не выбран</option>${Array.from({length:cols},(_,i)=>`<option value="${i}">${i+1}: ${esc(headers[i]||'без заголовка')}</option>`).join('')}</select></label>`).join('');for(const select of document.querySelectorAll('[data-map]')){const patterns={name:/назван|наимен|name/i,unit:/единиц|^ед\.?$|unit/i,price:/цена|price/i,supplier:/постав|supplier/i,article:/артикул|sku|article/i,source:/источник|source/i,note:/примеч|note/i};const i=headers.findIndex(s=>patterns[select.dataset.map].test(s));if(i>=0)select.value=String(i);}$('xlsx-sample').innerHTML='<table class="workspace-table">'+data.rows.slice(0,8).map(r=>'<tr><td>'+esc(r.number)+'</td>'+r.values.map((v,i)=>'<td>'+esc(v)+(r.formulas.includes(i)?' [формула]':'')+'</td>').join('')+'</tr>').join('')+'</table><p class="muted">Показаны первые 8 строк. Пропущено скрытых строк: '+data.skipped_hidden+'.</p>';$('xlsx-apply').disabled=true;$('xlsx-changes').innerHTML='';importChanges=[];}
async function previewExcel(){const mapping=Object.fromEntries(Array.from(document.querySelectorAll('[data-map]')).map(e=>[e.dataset.map,Number(e.value)]));const r=await api('/api/xlsx/map',{rows:importBook.rows,mapping,start:Number($('xlsx-start').value)-1,source:importFile+' / '+$('xlsx-sheet').selectedOptions[0].textContent,date:$('xlsx-date').value,supplier:$('xlsx-supplier').value});if(r.errors.length){$('xlsx-changes').innerHTML='<ul>'+r.errors.map(e=>`<li>Строка ${esc(e.row)}: ${esc(e.message)}</li>`).join('')+'</ul>';$('xlsx-apply').disabled=true;return;}importChanges=(await ws('import-preview',{rows:r.rows})).changes;$('xlsx-changes').innerHTML='<table class="workspace-table"><tr><th>Позиция</th><th>Было</th><th>Станет</th><th>Действие</th></tr>'+importChanges.map(x=>`<tr><td>${esc(x.name)}</td><td>${money(x.old_price)}</td><td>${money(x.data.price)}</td><td>${x.id?'Обновить':'Добавить'}</td></tr>`).join('')+'</table>';$('xlsx-apply').disabled=!importChanges.length;}
async function saveProfile(){const data={...formData($('profile-form')),logo:profile.logo||'',autosave:$('autosave-draft').checked};profileRecord=await ws('save',{kind:'profile',name:data.company||'Моя компания',data,id:profileRecord?.id,expected_revision:profileRecord?.revision});profile=profileRecord.data;notify('Реквизиты сохранены.');}
async function exportDocument(kind,client){const data=await api('/api/export-'+kind,{project:snapshot(),profile,client_view:client});download64(data.content,safeFilename(project.project.title)+(client?'_smeta':'_calculation')+'.'+kind,kind==='pdf'?'application/pdf':'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');notify('Документ подготовлен для сохранения.');}
async function saveDraft(){if(!$('autosave-draft').checked)return;if(draftSaving){draftPending=true;return;}draftSaving=true;try{do{draftPending=false;draftRecord=await ws('save',{kind:'draft',name:'Последний черновик',data:snapshot(),id:draftRecord?.id,expected_revision:draftRecord?.revision});$('draft-status').textContent='Черновик сохранён на компьютере: '+new Date().toLocaleTimeString('ru-RU');$('draft-recover').hidden=false;}while(draftPending&&$('autosave-draft').checked);}catch(e){$('draft-status').textContent='Черновик не обновлён: '+e.message;}finally{draftSaving=false;}}
function bindWorkspace(){
  $('own-new').onclick=()=>editCatalog(null);$('own-close').onclick=()=>$('own-dialog').close();$('own-form').onsubmit=saveCatalog;
  $('own-query').oninput=()=>refreshCatalog().catch(e=>notify(e.message,true));
  document.addEventListener('save-catalog-row',e=>{const row=project.rows[e.detail.index];editCatalog(null,{...row,supplier:'',article:''});});
  $('own-list').onclick=e=>{const b=e.target.closest('[data-own-action]');if(!b)return;guarded(b,async()=>{const item=ownItems.find(x=>x.id===b.dataset.id);if(!item)return;if(b.dataset.ownAction==='use'){setTab('estimate');editRow(null,{...item.data,id:crypto.randomUUID(),quantity:'',confirmed:false});}else if(b.dataset.ownAction==='edit')editCatalog(item);else if(b.dataset.ownAction==='source-document'){const result=await api('/api/prices/document',{document:item.data.price_observation.document});download64(result.content,result.filename,'application/octet-stream');}else if(confirm('Удалить расценку из справочника?')){await ws('delete',{kind:'catalog',id:item.id,expected_revision:item.revision});await refreshCatalog();}});};
  $('top-order-save').onclick=e=>guarded(e.currentTarget,saveOrder);$('order-save').onclick=e=>guarded(e.currentTarget,saveOrder);$('orders-query').oninput=()=>refreshOrders().catch(e=>notify(e.message,true));
  $('orders-list').onclick=e=>{const b=e.target.closest('[data-order-action]');if(!b)return;guarded(b,async()=>{const item=orders.find(x=>x.id===b.dataset.id),action=b.dataset.orderAction;if(action==='open'||action==='copy')await loadStored('order',item.id,null,action==='copy');else if(action==='versions'){const r=await ws('versions',{id:item.id});$('order-versions').hidden=false;$('order-versions').innerHTML='<h2>Версии: '+esc(item.name)+'</h2>'+r.versions.map(v=>`<button data-version="${v.revision}" data-order-id="${esc(item.id)}">Версия ${v.revision} · ${esc(v.updated.slice(0,16))}</button>`).join(' ');}else if(confirm('Удалить заказ вместе с его версиями?')){await ws('delete',{kind:'order',id:item.id,expected_revision:item.revision});if(currentOrder?.id===item.id)currentOrder=null;await refreshOrders();}});};
  $('order-versions').onclick=e=>{const b=e.target.closest('[data-version]');if(b)guarded(b,()=>loadStored('order',b.dataset.orderId,Number(b.dataset.version)));};
  $('template-form').onsubmit=e=>{e.preventDefault();guarded(e.target.querySelector('[type=submit]'),async()=>{if(!okayReplace())return;const data=await api('/api/template',formData(e.target));loadProject(data,'Черновик по шаблону. Уточните расценки и состав.');markDirty();setTab('estimate');});};
  $('operation-form').onsubmit=e=>{e.preventDefault();guarded(e.target.querySelector('[type=submit]'),async()=>{const original=project,r=await api('/api/operation',formData(e.target));const copy=snapshot();copy.rows.push(r.row);await api('/api/calculate',copy);if(project!==original)throw Error('Заказ изменился. Повторите добавление операции.');project.rows.push(r.row);markDirty();renderRows();scheduleCalculate(0);notify('Операция добавлена: '+r.hours+' ч. Источник ставки и её состав подтвердите в карточке позиции.');});};
  $('template-save').onclick=e=>guarded(e.currentTarget,()=>saveNamed('template','Название шаблона'));
  $('templates-list').onclick=e=>{const b=e.target.closest('[data-template-action]');if(!b)return;guarded(b,async()=>{const item=templateItems.find(x=>x.id===b.dataset.id);if(b.dataset.templateAction==='use'){if(!okayReplace())return;const data=structuredClone(item.data);data.rows.forEach(r=>{r.id=crypto.randomUUID();r.confirmed=false;});data.extensions={};loadProject(data,'Новый заказ по собственному шаблону. Проверьте количества и цены.');markDirty();setTab('estimate');}else if(confirm('Удалить шаблон?')){await ws('delete',{kind:'template',id:item.id,expected_revision:item.revision});await refreshTemplates();}});};
  $('variant-save').onclick=e=>guarded(e.currentTarget,()=>saveNamed('variant','Название варианта, например 500 шт.'));
  $('variants-calculate').onclick=e=>guarded(e.currentTarget,compareVariants);
  $('variants-list').onclick=e=>{const b=e.target.closest('[data-variant-action]');if(!b)return;guarded(b,async()=>{const item=variants.find(x=>x.id===b.dataset.id);if(b.dataset.variantAction==='open')await loadStored('variant',item.id,null,true);else if(confirm('Удалить вариант?')){await ws('delete',{kind:'variant',id:item.id,expected_revision:item.revision});await refreshVariants();}});};
  $('offer-form').onsubmit=e=>{e.preventDefault();guarded(e.target.querySelector('[type=submit]'),async()=>{const data=formData(e.target);for(const k of ['price','delivery','increment','minimum'])data[k]=decimalInput(data[k]);await ws('save',{kind:'offer',name:data.supplier+' / '+data.item,data,id:offerEdit?.id,expected_revision:offerEdit?.revision});offerEdit=null;e.target.reset();await refreshOffers();notify('Предложение сохранено.');});};
  $('offer-clear').onclick=()=>{offerEdit=null;$('offer-form').reset();};$('offers-list').onclick=e=>{const b=e.target.closest('[data-offer-action]');if(!b)return;guarded(b,async()=>{const item=offers.find(x=>x.id===b.dataset.id);if(b.dataset.offerAction==='edit'){offerEdit=item;fill($('offer-form'),item.data);}else if(confirm('Удалить предложение?')){await ws('delete',{kind:'offer',id:item.id,expected_revision:item.revision});await refreshOffers();}});};$('offers-calculate').onclick=e=>guarded(e.currentTarget,compareOffers);
  $('actual-table').oninput=e=>{const id=e.target.dataset.actualId;if(!id)return;const ext=extras();ext.actuals[id]??={amount:'',note:''};ext.actuals[id][e.target.dataset.key]=e.target.dataset.key==='amount'?decimalInput(e.target.value):e.target.value;markDirty();$('actual-result').innerHTML='';};
  $('actual-extra').oninput=()=>{extras().extra_actual=decimalInput($('actual-extra').value);markDirty();$('actual-result').innerHTML='';};$('actual-extra-note').oninput=()=>{extras().extra_note=$('actual-extra-note').value;markDirty();};$('actual-calculate').onclick=e=>guarded(e.currentTarget,calculateActual);
  $('own-import').onclick=()=>{$('xlsx-panel').hidden=false;$('xlsx-file').click();};$('xlsx-file').onchange=()=>readExcel().catch(e=>notify(e.message,true));$('xlsx-sheet').onchange=()=>readSheet(Number($('xlsx-sheet').value)).catch(e=>notify(e.message,true));
  $('xlsx-preview').onclick=e=>guarded(e.currentTarget,previewExcel);$('xlsx-panel').addEventListener('input',()=>{$('xlsx-apply').disabled=true;importChanges=[];});
  $('xlsx-apply').onclick=e=>guarded(e.currentTarget,async()=>{const r=await ws('import-apply',{changes:importChanges});importChanges=[];$('xlsx-changes').textContent='Сохранено позиций: '+r.saved;await refreshCatalog();setTimeout(()=>$('xlsx-apply').disabled=true,0);notify('Импорт завершён. Новые цены требуют проверки для конкретного заказа.');});
  $('profile-form').onsubmit=e=>{e.preventDefault();guarded(e.target.querySelector('[type=submit]'),saveProfile);};$('company-logo').onchange=async()=>{try{const file=$('company-logo').files[0];if(!file)return;if(file.size>1048576||!['image/png','image/jpeg'].includes(file.type))throw Error('Нужен PNG или JPEG до 1 МБ.');profile.logo='data:'+file.type+';base64,'+await bytes64(file);$('logo-status').textContent='Выбран: '+file.name+'. Нажмите «Сохранить реквизиты».';}catch(e){notify(e.message,true);}};$('logo-clear').onclick=()=>{profile.logo='';$('logo-status').textContent='Логотип убран. Сохраните реквизиты.';};
  for(const [id,kind,client]of [['pdf-client','pdf',true],['xlsx-client','xlsx',true],['pdf-internal','pdf',false],['xlsx-internal','xlsx',false]])$(id).onclick=e=>guarded(e.currentTarget,()=>exportDocument(kind,client));
  $('autosave-draft').onchange=async()=>{try{profileRecord=await ws('save',{kind:'profile',name:profile.company||'Моя компания',data:{...profile,autosave:$('autosave-draft').checked},id:profileRecord?.id,expected_revision:profileRecord?.revision});profile=profileRecord.data;if($('autosave-draft').checked)saveDraft();else{clearTimeout(draftTimer);$('draft-status').textContent='Автосохранение черновика выключено.';}}catch(e){notify(e.message,true);}};
  document.addEventListener('estimate-change',()=>{clearTimeout(draftTimer);if($('autosave-draft').checked)draftTimer=setTimeout(saveDraft,1200);});
  document.addEventListener('estimate-loaded',()=>{currentOrder=null;clearTimeout(draftTimer);});
  $('draft-recover').onclick=e=>guarded(e.currentTarget,async()=>{if(!draftRecord||!okayReplace())return;const record=await ws('get',{kind:'draft',id:draftRecord.id});loadProject(record.data,'Восстановлен локальный черновик.');markDirty();setTab('estimate');});
  $('backup-save').onclick=e=>guarded(e.currentTarget,async()=>{download(JSON.stringify(await ws('backup'),null,2),'estimator_backup_'+new Date().toISOString().slice(0,10)+'.json','application/json');});$('backup-open').onclick=()=>$('backup-file').click();$('backup-file').onchange=async()=>{try{const file=$('backup-file').files[0];if(!file)return;if(file.size>60000000)throw Error('Копия превышает 60 МБ.');const data=JSON.parse(await file.text());if(!confirm('Добавить записи резервной копии как отдельные копии? Текущие записи останутся.'))return;const r=await ws('restore',data);notify(r.note+' Добавлено: '+r.imported);await refreshOrders();}catch(e){notify(e.message,true);}finally{$('backup-file').value='';}};
  $('ollama-refresh').onclick=e=>guarded(e.currentTarget,async()=>{const r=await api('/api/assistant/models',{});$('ollama-model').innerHTML=r.models.map(name=>`<option>${esc(name)}</option>`).join('')||'<option value="">Локальные GGUF-модели не найдены</option>';});
  $('assistant-form').onsubmit=e=>{e.preventDefault();guarded(e.target.querySelector('[type=submit]'),async()=>{const r=await api('/api/assistant/draft',formData(e.target));fill($('template-form'),r.parameters);$('assistant-result').innerHTML='<p>'+esc(r.mode)+'</p><p>Параметры перенесены в форму шаблона. '+(r.questions.length?'Нужно уточнить: '+esc(r.questions.join(', '))+'.':'Проверьте значения перед созданием сметы.')+' Проверьте монтаж, доставку, ламинацию, запас и формат листа.</p><button id="assistant-template" type="button">Проверить параметры шаблона</button>';$('assistant-template').onclick=()=>{setTab('production');refreshTemplates().catch(e=>notify(e.message,true));};});};
}
async function init(){if(initialized)return;initialized=true;addMarkup();bindWorkspace();try{const [p,d]=await Promise.all([ws('list',{kind:'profile'}),ws('list',{kind:'draft'})]);profileRecord=p.items[0]||null;profile=profileRecord?.data||{};$('autosave-draft').checked=!!profile.autosave;fill($('profile-form'),profile);$('logo-status').textContent=profile.logo?'Логотип сохранён.':'';draftRecord=d.items[0]||null;$('draft-recover').hidden=!draftRecord;$('draft-status').textContent=draftRecord?'Есть сохранённый черновик. Можно восстановить его.':'Автосохранение включается по вашему выбору.';}catch(e){notify('Локальная база: '+e.message,true);}}
document.addEventListener('estimator-ready',init);if(typeof boot!=='undefined'&&boot&&typeof project!=='undefined'&&project)init();
document.addEventListener('price-catalog-updated',()=>refreshCatalog().catch(e=>notify(e.message,true)));
})();
